spring:
  application:
    name: planner
  datasource:
    url: jdbc:postgresql://localhost:5432/planner
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
    default-schema: public

server:
  port: 8080
